# Generated by Django 4.2.3 on 2023-07-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='discussion',
        ),
    ]
